/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
/* Header for class com_test_git_jnidemo_JniUtil_CatchThrow */

#ifndef _Included_com_test_git_jnidemo_JniUtil_CatchThrow
#define _Included_com_test_git_jnidemo_JniUtil_CatchThrow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_git_jnidemo_JniUtil_CatchThrow
 * Method:    doit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_CatchThrow_doit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}

void JUN_ThrowByName(JNIEnv *, const char*, const char*);

jvalue JUN_CallMethodByName(JNIEnv *, jboolean *, jobject, const char*, const char*, ...);

#endif
#endif
