/* DO NOT EDIT THIS FILE - it is machine generated */
#define _CRT_SECURE_NO_WARNINGS
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
/* Header for class com_test_git_jnidemo_JniUtil_JniDemo */

#ifndef _Included_com_test_git_jnidemo_JniUtil_JniDemo
#define _Included_com_test_git_jnidemo_JniUtil_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_git_jnidemo_JniUtil_JniDemo
 * Method:    helloJni
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_helloJni
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_helloJniStatic
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_accessField
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_accessArrayField
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_accessStaticField
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_accessMethod
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_accessStaticMethod
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_accessConstructMethod
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_accessParentMethod
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_passArrayMethod
(JNIEnv *, jobject, jintArray);

JNIEXPORT jintArray JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_createArrayMethod
(JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_cacheFieldWhenUse
(JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_cacheMethodWhenUse
        (JNIEnv *, jobject, jcharArray);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_cacheWhenInit
        (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_cacheWhenInitInvoke
        (JNIEnv *, jobject, jcharArray);

JNIEXPORT void JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_createGlobalRef
        (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_test_git_jnidemo_JniUtil_JniDemo_useGlobalRef
        (JNIEnv *, jobject, jcharArray);

jstring MyNewString(JNIEnv *, jchar, jint len);

#ifdef __cplusplus
}
#endif
#endif
